spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    profiles:
        include: secret
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
