cloud:
    aws:
        credentials:
            accessKey: AKIA4FLHRG6OBMXV3O5N
            secretKey: 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
        region:
            static: ap-northeast-2
        s3:
            bucket: pin-clone-bucket
        stack:
            auto: false
jwt:
    secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/post
        username: root

google:
    client:
        id: 319129422173-g60i3edah1vpcleafnuc96cvhv0udmor.apps.googleusercontent.com
        pw: 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
        redirect: http://localhost:8080/login/oauth2/code/google
        api: AIzaSyDxsbP-EUKMObk0Igxe-Ful618k-edZxKw
