cloud:
    aws:
        credentials:
            accessKey: AKIA4FLHRG6OOUTRQ3W4
            secretKey: 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
        region:
            static: ap-northeast-2
        s3:
            bucket: pin-clone-bucket
        stack:
            auto: false
jwt:
    secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 190409
        url: jdbc:mysql://localhost:3306/pinterest
        username: root
